/* Auto-generated from 언론보도송출마케팅_송출단가표.xlsx */
window.DELIVER_MEDIA_SEED_VERSION = "2026-02-23-media-xlsx-v1";
window.DELIVER_MEDIA_SEED = [
  {
    "id": "media_seed_001",
    "name": "시민일보",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 50000,
    "memberPrice": "50,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산 // 연혁 3년 이상인 업체만 송출 가능(사업자등록증 첨부 필수)",
    "isActive": true
  },
  {
    "id": "media_seed_002",
    "name": "컨슈머타임스",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 50000,
    "memberPrice": "50,000원",
    "channel": "네이버",
    "description": "불가 업종 : 부동산 // 명확한 이슈가 있는 기사에 한해 진행 가능",
    "isActive": true
  },
  {
    "id": "media_seed_003",
    "name": "한국목재신문",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 50000,
    "memberPrice": "50,000원",
    "channel": "네이버 다음/네이트",
    "description": "동일 주제의 경우 1-2주 텀으로 진행",
    "isActive": true
  },
  {
    "id": "media_seed_004",
    "name": "데일리시큐",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 50000,
    "memberPrice": "50,000원",
    "channel": "네이버",
    "description": "불가 업종 : 부동산 // IT·과학 관련 기사만 다음 노출 가능",
    "isActive": true
  },
  {
    "id": "media_seed_005",
    "name": "공감신문",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 50000,
    "memberPrice": "50,000원",
    "channel": "네이버",
    "description": "불가 업종: 부동산 // 편집 강도 높은 편",
    "isActive": true
  },
  {
    "id": "media_seed_006",
    "name": "핸드메이커",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 50000,
    "memberPrice": "50,000원",
    "channel": "네이버",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_007",
    "name": "내외경제TV",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 50000,
    "memberPrice": "50,000원",
    "channel": "네이버",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_008",
    "name": "피앤피뉴스",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 60000,
    "memberPrice": "60,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_009",
    "name": "데일리경제",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 60000,
    "memberPrice": "60,000원",
    "channel": "네이버",
    "description": "불가 업종 : 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_010",
    "name": "울산제일일보",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 60000,
    "memberPrice": "60,000원",
    "channel": "네이버",
    "description": "불가 업종 : 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_011",
    "name": "뉴스로드",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 60000,
    "memberPrice": "60,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_012",
    "name": "라***뉴스",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 60000,
    "memberPrice": "60,000원",
    "channel": "네이버",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_013",
    "name": "**일보",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 60000,
    "memberPrice": "60,000원",
    "channel": "네이버",
    "description": "* 부동산 기사의 경우 상품1 단가로 진행",
    "isActive": true
  },
  {
    "id": "media_seed_014",
    "name": "시선뉴스",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 70000,
    "memberPrice": "70,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종 : 부동산 // 대중문화·연예·스포츠 관련 기사는 다음 노출 불가",
    "isActive": true
  },
  {
    "id": "media_seed_015",
    "name": "글로벌에픽",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 72000,
    "memberPrice": "72,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종 : 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_016",
    "name": "데일리팝",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 72000,
    "memberPrice": "72,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산 // 명확한 이슈가 있는 기사에 한해 진행 가능",
    "isActive": true
  },
  {
    "id": "media_seed_017",
    "name": "더파워",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 72000,
    "memberPrice": "72,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_018",
    "name": "비**포스트",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 72000,
    "memberPrice": "72,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종 : 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_019",
    "name": "빅데이터뉴스",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 72000,
    "memberPrice": "72,000원",
    "channel": "네이버",
    "description": "불가 업종 : 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_020",
    "name": "아이티비즈",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 72000,
    "memberPrice": "72,000원",
    "channel": "네이버",
    "description": "불가 업종 : 부동산 // 제목 수정·삭제 시 1회 송출 비용 발생",
    "isActive": true
  },
  {
    "id": "media_seed_021",
    "name": "에너지경제",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 72000,
    "memberPrice": "72,000원",
    "channel": "네이버",
    "description": "* 부동산 기사의 경우 상품1 단가로 진행",
    "isActive": true
  },
  {
    "id": "media_seed_022",
    "name": "트래블바이크뉴스",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 72000,
    "memberPrice": "72,000원",
    "channel": "다음/네이트",
    "description": "불가 업종 : 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_023",
    "name": "경북신문",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 72000,
    "memberPrice": "72,000원",
    "channel": "네이버",
    "description": "* 부동산 기사의 경우 상품1 단가로 진행",
    "isActive": true
  },
  {
    "id": "media_seed_024",
    "name": "한국**뉴스",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 72000,
    "memberPrice": "72,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종 : 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_025",
    "name": "더퍼스트",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 72000,
    "memberPrice": "72,000원",
    "channel": "네이버",
    "description": "* 부동산 기사의 경우 상품1 단가로 진행 // 편집 강도 높은 편",
    "isActive": true
  },
  {
    "id": "media_seed_026",
    "name": "한국영농신문",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 72000,
    "memberPrice": "72,000원",
    "channel": "네이버",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_027",
    "name": "직썰",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 72000,
    "memberPrice": "72,000원",
    "channel": "네이버",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_028",
    "name": "매일안전신문",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 72000,
    "memberPrice": "72,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종 : 부동산 // 인물 독사진 불가",
    "isActive": true
  },
  {
    "id": "media_seed_029",
    "name": "문학뉴스",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 72000,
    "memberPrice": "72,000원",
    "channel": "네이버",
    "description": "수정 시 1회 송출 비용 발생",
    "isActive": true
  },
  {
    "id": "media_seed_030",
    "name": "대학저널",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 72000,
    "memberPrice": "72,000원",
    "channel": "네이버 다음/네이트",
    "description": "학교",
    "isActive": true
  },
  {
    "id": "media_seed_031",
    "name": "여성소비자신문",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 72000,
    "memberPrice": "72,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_032",
    "name": "테크월드",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 72000,
    "memberPrice": "72,000원",
    "channel": "네이버",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_033",
    "name": "대한금융신문",
    "category": "C급",
    "bylineType": "기명",
    "unitPrice": 72000,
    "memberPrice": "72,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_034",
    "name": "데이터넷",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 90000,
    "memberPrice": "90,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_035",
    "name": "에듀동아",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 90000,
    "memberPrice": "90,000원",
    "channel": "네이버 다음/네이트",
    "description": "교육 관련 기사만 가능",
    "isActive": true
  },
  {
    "id": "media_seed_036",
    "name": "증권경제신문",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 90000,
    "memberPrice": "90,000원",
    "channel": "네이버 다음/네이트",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_037",
    "name": "스포츠W",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 90000,
    "memberPrice": "90,000원",
    "channel": "네이버",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_038",
    "name": "하비엔",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 90000,
    "memberPrice": "90,000원",
    "channel": "네이버 다음/네이트",
    "description": "* 부동산 기사의 경우 상품1 단가로 진행",
    "isActive": true
  },
  {
    "id": "media_seed_039",
    "name": "인터뷰365",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 90000,
    "memberPrice": "90,000원",
    "channel": "네이버",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_040",
    "name": "시사매거진",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 90000,
    "memberPrice": "90,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_041",
    "name": "필드뉴스",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 90000,
    "memberPrice": "90,000원",
    "channel": "네이버",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_042",
    "name": "한국금융경제신문",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 90000,
    "memberPrice": "90,000원",
    "channel": "네이버",
    "description": "불가 업종: 부동산 // 수정·삭제 시 1회 송출 비용 발생",
    "isActive": true
  },
  {
    "id": "media_seed_043",
    "name": "메가경제",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 90000,
    "memberPrice": "90,000원",
    "channel": "네이버 다음/네이트",
    "description": "* 부동산 기사의 경우 상품1 단가로 진행",
    "isActive": true
  },
  {
    "id": "media_seed_044",
    "name": "소셜밸류",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 90000,
    "memberPrice": "90,000원",
    "channel": "네이버",
    "description": "* 부동산 기사의 경우 상품1 단가로 진행",
    "isActive": true
  },
  {
    "id": "media_seed_045",
    "name": "뉴스컬처",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 90000,
    "memberPrice": "90,000원",
    "channel": "네이버 다음/네이트",
    "description": "* 부동산 기사의 경우 상품1 단가로 진행 // 송출 후 수정 불가",
    "isActive": true
  },
  {
    "id": "media_seed_046",
    "name": "어린이동아",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 120000,
    "memberPrice": "120,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산 // 유아·어린이 관련 기사만 가능",
    "isActive": true
  },
  {
    "id": "media_seed_047",
    "name": "잡포스트",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 120000,
    "memberPrice": "120,000원",
    "channel": "네이버",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_048",
    "name": "패션비즈",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 120000,
    "memberPrice": "120,000원",
    "channel": "네이버",
    "description": "패션 관련 기사만 가능 / 송출 후 수정 불가 (1개월 지난 기사는 삭제도 불가)",
    "isActive": true
  },
  {
    "id": "media_seed_049",
    "name": "파이낸스투데이",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 120000,
    "memberPrice": "120,000원",
    "channel": "네이버",
    "description": "* 부동산 기사의 경우 상품1 단가로 진행",
    "isActive": true
  },
  {
    "id": "media_seed_050",
    "name": "굿모닝경제",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 120000,
    "memberPrice": "120,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_051",
    "name": "제민일보",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 120000,
    "memberPrice": "120,000원",
    "channel": "네이버",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_052",
    "name": "이투뉴스",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 120000,
    "memberPrice": "120,000원",
    "channel": "네이버 다음/네이트",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_053",
    "name": "문화뉴스",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 120000,
    "memberPrice": "120,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_054",
    "name": "IT비즈뉴스",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 120000,
    "memberPrice": "120,000원",
    "channel": "네이버",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_055",
    "name": "국제뉴스",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 120000,
    "memberPrice": "120,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_056",
    "name": "한국정경신문",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 120000,
    "memberPrice": "120,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종 : 부동산 // 확실한 사유 없이 기사 삭제 불가",
    "isActive": true
  },
  {
    "id": "media_seed_057",
    "name": "아웃도어뉴스",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 120000,
    "memberPrice": "120,000원",
    "channel": "네이버 다음/네이트",
    "description": "아웃도어·캠핑 관련 기사만 가능 ※퀄리티 좋은 일부 기사의 경우 아웃도어 매거진에 동시 노출",
    "isActive": true
  },
  {
    "id": "media_seed_058",
    "name": "스마트투데이",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 120000,
    "memberPrice": "120,000원",
    "channel": "네이버",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_059",
    "name": "딜라이트닷넷",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 120000,
    "memberPrice": "120,000원",
    "channel": "네이버",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_060",
    "name": "AP신문",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 140000,
    "memberPrice": "140,000원",
    "channel": "네이버",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_061",
    "name": "헬로티",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 140000,
    "memberPrice": "140,000원",
    "channel": "네이버",
    "description": "이미지에 업체 이름 노출 불가",
    "isActive": true
  },
  {
    "id": "media_seed_062",
    "name": "데이터뉴스",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 140000,
    "memberPrice": "140,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종 : 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_063",
    "name": "스****",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 140000,
    "memberPrice": "140,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_064",
    "name": "이넷뉴스",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 140000,
    "memberPrice": "140,000원",
    "channel": "네이버 다음/네이트",
    "description": "깔끔한 경제 및 산업 관련 기사만 가능",
    "isActive": true
  },
  {
    "id": "media_seed_065",
    "name": "비지니스코리아",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 140000,
    "memberPrice": "140,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_066",
    "name": "글로벌경제",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 140000,
    "memberPrice": "140,000원",
    "channel": "네이버",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_067",
    "name": "나무신문",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 140000,
    "memberPrice": "140,000원",
    "channel": "네이버",
    "description": "부동산 기사만 가능",
    "isActive": true
  },
  {
    "id": "media_seed_068",
    "name": "뉴스핌",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 140000,
    "memberPrice": "140,000원",
    "channel": "네이버 다음/네이트",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_069",
    "name": "마켓뉴스",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 140000,
    "memberPrice": "140,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_070",
    "name": "서울***비",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 140000,
    "memberPrice": "140,000원",
    "channel": "네이버 다음/네이트",
    "description": "접수 전 송출 가능일자 확인 요망",
    "isActive": true
  },
  {
    "id": "media_seed_071",
    "name": "아시아투데이",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 160000,
    "memberPrice": "160,000원",
    "channel": "네이버",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_072",
    "name": "전민일보",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 160000,
    "memberPrice": "160,000원",
    "channel": "네이버 다음/네이트",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_073",
    "name": "뉴스퀘스트",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 160000,
    "memberPrice": "160,000원",
    "channel": "네이버 다음/네이트",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_074",
    "name": "새전북신문",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 160000,
    "memberPrice": "160,000원",
    "channel": "네이버 다음/네이트",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_075",
    "name": "이투데이",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 160000,
    "memberPrice": "160,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_076",
    "name": "이로운넷",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 160000,
    "memberPrice": "160,000원",
    "channel": "네이버 다음/네이트",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_077",
    "name": "아시아타임즈",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 160000,
    "memberPrice": "160,000원",
    "channel": "네이버 다음/네이트",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_078",
    "name": "키즈맘",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 160000,
    "memberPrice": "160,000원",
    "channel": "네이버 다음/네이트",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_079",
    "name": "스포츠월드 뉴스콘텐츠",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 160000,
    "memberPrice": "160,000원",
    "channel": "네이버",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_080",
    "name": "세계비즈",
    "category": "B급",
    "bylineType": "기명",
    "unitPrice": 160000,
    "memberPrice": "160,000원",
    "channel": "네이버 다음/네이트",
    "description": "* 부동산 기사의 경우 상품1 단가로 진행",
    "isActive": true
  },
  {
    "id": "media_seed_081",
    "name": "파이낸셜포스트",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 180000,
    "memberPrice": "180,000원",
    "channel": "네이버",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_082",
    "name": "아주경제",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 180000,
    "memberPrice": "180,000원",
    "channel": "네이버",
    "description": "불가 업종: 부동산 // 삭제 불가",
    "isActive": true
  },
  {
    "id": "media_seed_083",
    "name": "월간암",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 180000,
    "memberPrice": "180,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종 : 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_084",
    "name": "뉴스워커",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 180000,
    "memberPrice": "180,000원",
    "channel": "네이버 다음/네이트",
    "description": "* 부동산 기사의 경우 상품1 단가로 진행",
    "isActive": true
  },
  {
    "id": "media_seed_085",
    "name": "마니아타임즈 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 180000,
    "memberPrice": "180,000원",
    "channel": "네이버 다음/네이트",
    "description": "스포츠",
    "isActive": true
  },
  {
    "id": "media_seed_086",
    "name": "데일리한국",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 200000,
    "memberPrice": "200,000원",
    "channel": "네이버 다음/네이트",
    "description": "* 부동산 기사의 경우 상품1 단가로 진행",
    "isActive": true
  },
  {
    "id": "media_seed_087",
    "name": "스포츠한국",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 200000,
    "memberPrice": "200,000원",
    "channel": "네이버",
    "description": "* 부동산 기사의 경우 상품1 단가로 진행",
    "isActive": true
  },
  {
    "id": "media_seed_088",
    "name": "넥스트데일리",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 200000,
    "memberPrice": "200,000원",
    "channel": "네이버 다음/네이트",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_089",
    "name": "국토일보",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 200000,
    "memberPrice": "200,000원",
    "channel": "네이버 다음/네이트",
    "description": "건설·부동산 관련 기사만 가능",
    "isActive": true
  },
  {
    "id": "media_seed_090",
    "name": "MK스포츠 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 200000,
    "memberPrice": "200,000원",
    "channel": "네이버 다음/네이트",
    "description": "연예·스포츠 관련 기사만 가능",
    "isActive": true
  },
  {
    "id": "media_seed_091",
    "name": "텐아시아 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 210000,
    "memberPrice": "210,000원",
    "channel": "네이버 다음/네이트",
    "description": "연예 관련 기사만 가능",
    "isActive": true
  },
  {
    "id": "media_seed_092",
    "name": "MBN(매일방송) 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 210000,
    "memberPrice": "210,000원",
    "channel": "네이버 다음/네이트",
    "description": "연예·스포츠 관련 기사만 가능",
    "isActive": true
  },
  {
    "id": "media_seed_093",
    "name": "매**문 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 250000,
    "memberPrice": "250,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_094",
    "name": "스***향 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 250000,
    "memberPrice": "250,000원",
    "channel": "네이버 다음/네이트",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_095",
    "name": "마이데일리 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 280000,
    "memberPrice": "280,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_096",
    "name": "뉴스1 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 280000,
    "memberPrice": "280,000원",
    "channel": "네이버 다음/네이트",
    "description": "* 부동산 기사의 경우 상품1 단가로 진행 // 언론사 가이드에 맞게 임의 편집되며 수정 및 삭제 불가",
    "isActive": true
  },
  {
    "id": "media_seed_097",
    "name": "디지털타임스 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 280000,
    "memberPrice": "280,000원",
    "channel": "네이버 다음/네이트",
    "description": "* 부동산 기사의 경우 상품1 단가로 진행",
    "isActive": true
  },
  {
    "id": "media_seed_098",
    "name": "한***** 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 330000,
    "memberPrice": "330,000원",
    "channel": "네이버 다음/네이트",
    "description": "미용 관련 키워드 불가",
    "isActive": true
  },
  {
    "id": "media_seed_099",
    "name": "조세일보 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 330000,
    "memberPrice": "330,000원",
    "channel": "네이버 다음/네이트",
    "description": "수정·삭제 시 1회 송출 비용 발생",
    "isActive": true
  },
  {
    "id": "media_seed_100",
    "name": "데일리안 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 330000,
    "memberPrice": "330,000원",
    "channel": "네이버 다음/네이트",
    "description": "* 부동산 기사의 경우 상품1 단가로 진행",
    "isActive": true
  },
  {
    "id": "media_seed_101",
    "name": "이**리 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 330000,
    "memberPrice": "330,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산 // 삭제 불가",
    "isActive": true
  },
  {
    "id": "media_seed_102",
    "name": "중앙SUNDAY 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 340000,
    "memberPrice": "340,000원",
    "channel": "네이버",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_103",
    "name": "헤럴드경제 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 340000,
    "memberPrice": "340,000원",
    "channel": "네이버 다음/네이트",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_104",
    "name": "건강다이제스트",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 340000,
    "memberPrice": "340,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_105",
    "name": "IT조선",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 340000,
    "memberPrice": "340,000원",
    "channel": "네이버",
    "description": "불가 업종 : 부동산 // 삭제 시 1회 송출 비용 발생 / 편집 강도 높은 편",
    "isActive": true
  },
  {
    "id": "media_seed_106",
    "name": "**신문 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 350000,
    "memberPrice": "350,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_107",
    "name": "파이낸셜뉴스 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 350000,
    "memberPrice": "350,000원",
    "channel": "네이버 다음/네이트",
    "description": "* 부동산 기사의 경우 상품1 단가로 진행",
    "isActive": true
  },
  {
    "id": "media_seed_108",
    "name": "세계일보 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 350000,
    "memberPrice": "350,000원",
    "channel": "네이버 다음/네이트",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_109",
    "name": "스포츠서울 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 380000,
    "memberPrice": "380,000원",
    "channel": "네이버",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_110",
    "name": "서울경제 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 380000,
    "memberPrice": "380,000원",
    "channel": "네이버 다음/네이트",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_111",
    "name": "조선에듀",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 380000,
    "memberPrice": "380,000원",
    "channel": "네이버 다음/네이트",
    "description": "교육 관련 기사만 가능",
    "isActive": true
  },
  {
    "id": "media_seed_112",
    "name": "서울신문 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 380000,
    "memberPrice": "380,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_113",
    "name": "아시아경제 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 500000,
    "memberPrice": "500,000원",
    "channel": "네이버 다음/네이트",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_114",
    "name": "국민일보 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 500000,
    "memberPrice": "500,000원",
    "channel": "네이버 다음/네이트",
    "description": "불가 업종: 부동산",
    "isActive": true
  },
  {
    "id": "media_seed_115",
    "name": "땅집고",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 520000,
    "memberPrice": "520,000원",
    "channel": "네이버 다음/네이트",
    "description": "부동산 기사만 가능",
    "isActive": true
  },
  {
    "id": "media_seed_116",
    "name": "H경제 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 550000,
    "memberPrice": "550,000원",
    "channel": "네이버 다음/네이트",
    "description": "* 기명 송출 원하는 경우 별도 문의",
    "isActive": true
  },
  {
    "id": "media_seed_117",
    "name": "YTN 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 550000,
    "memberPrice": "550,000원",
    "channel": "네이버 다음/네이트",
    "description": "* 부동산 기사의 경우 상품1 단가로 진행",
    "isActive": true
  },
  {
    "id": "media_seed_118",
    "name": "**경제 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 700000,
    "memberPrice": "700,000원",
    "channel": "네이버 다음/네이트",
    "description": "사진설명 및 출처 반드시 표기 / 단독 보도자료만 가능",
    "isActive": true
  },
  {
    "id": "media_seed_119",
    "name": "C비즈 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 700000,
    "memberPrice": "700,000원",
    "channel": "네이버",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_120",
    "name": "동아일보 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 700000,
    "memberPrice": "700,000원",
    "channel": "네이버 다음/네이트",
    "description": "",
    "isActive": true
  },
  {
    "id": "media_seed_121",
    "name": "중앙일보 뉴스콘텐츠",
    "category": "A급",
    "bylineType": "기명",
    "unitPrice": 800000,
    "memberPrice": "800,000원",
    "channel": "네이버 다음/네이트",
    "description": "",
    "isActive": true
  }
];
